// Remove Duplicate English Audio Streams
// Generated by Cline Audio Channel Manager v1.0.0
// 
// This plugin analyzes audio streams in media files and identifies duplicate
// English audio tracks. It will skip processing if:
// - No audio streams are found
// - No English streams are found  
// - Only one English stream exists
// - Undefined language streams are present (to avoid data loss)
//
// When multiple English streams are detected, it prepares the file for processing
// by the companion processor plugin.

const details = () => ({
  id: "Cline_Audio_English_Deduplicator",
  Stage: "Pre-processing",
  Name: "Remove Duplicate English Audio Streams",
  Type: "Audio",
  Operation: "Transcode",
  Description: "Keeps only the first English audio track while preserving all other languages",
  Version: "1.0.0",
  Tags: "pre-processing,audio,english,deduplication",
  Inputs: []
});

const plugin = (file, librarySettings, inputs, otherArguments) => {
  const response = {
    processFile: false,
    preset: "",
    container: "",
    handBrakeMode: false,
    FFmpegMode: false,
    reQueueAfter: false,
    infoLog: ""
  };

  try {
    // Get audio streams from file metadata
    const audioStreams = file.ffProbeData.streams.filter(stream => stream.codec_type === 'audio');
    
    if (audioStreams.length === 0) {
      response.infoLog += "❓ No audio streams found - skipping\n";
      return response;
    }

    response.infoLog += `✓ Found ${audioStreams.length} audio streams\n`;

    // Analyze audio streams by language
    const analysis = {
      englishStreams: [],
      otherLanguageStreams: [],
      undefinedStreams: []
    };

    audioStreams.forEach((stream, index) => {
      const tags = stream.tags || {};
      const language = (tags.language || 'und').toLowerCase();
      const channels = stream.channels || 0;
      const codec = stream.codec_name || 'unknown';
      
      response.infoLog += `Stream ${index}: ${codec} (${channels}ch) - ${language}\n`;

      if (language === 'eng' || language === 'en' || language === 'english') {
        analysis.englishStreams.push({
          index: stream.index,
          streamIndex: index,
          language: language,
          channels: channels,
          codec: codec
        });
      } else if (language === 'und' || language === 'undefined') {
        analysis.undefinedStreams.push({
          index: stream.index,
          streamIndex: index,
          language: language,
          channels: channels,
          codec: codec
        });
      } else {
        analysis.otherLanguageStreams.push({
          index: stream.index,
          streamIndex: index,
          language: language,
          channels: channels,
          codec: codec
        });
      }
    });

    // Decision logic - skip processing in these cases:
    
    // Skip if undefined language streams exist (avoid data loss)
    if (analysis.undefinedStreams.length > 0) {
      response.infoLog += "⚠️ Found undefined language streams - skipping to avoid data loss\n";
      return response;
    }

    // Skip if no English streams found
    if (analysis.englishStreams.length === 0) {
      response.infoLog += "⚠️ No English audio streams found - skipping\n";
      return response;
    }

    // Skip if only one English stream (no duplicates)
    if (analysis.englishStreams.length === 1) {
      response.infoLog += "✓ Only one English audio stream - no deduplication needed\n";
      return response;
    }

    // Multiple English streams detected - processing needed
    response.infoLog += `🔄 Multiple English streams detected (${analysis.englishStreams.length}) - deduplication needed\n`;
    response.infoLog += `✓ Keeping first English stream (index ${analysis.englishStreams[0].index})\n`;
    response.infoLog += `✓ Keeping ${analysis.otherLanguageStreams.length} other language streams\n`;
    response.infoLog += `❌ Removing ${analysis.englishStreams.length - 1} duplicate English streams\n`;

    // Set up for processing
    response.processFile = true;
    response.preset = `-f matroska`;
    response.container = file.container;
    response.handBrakeMode = false;
    response.FFmpegMode = false;
    response.reQueueAfter = true;

    return response;

  } catch (error) {
    response.infoLog += `❌ Error analyzing audio streams: ${error.message}\n`;
    return response;
  }
};

module.exports.details = details;
module.exports.plugin = plugin;
