// Process Audio Stream Removal
// Generated by Cline Audio Channel Manager v1.0.0
//
// This plugin processes media files to remove duplicate English audio streams.
// It uses MKVToolsNix for MKV files and FFmpeg for MP4 and other formats.
// 
// The plugin will:
// - Keep only the first English audio track
// - Preserve all other language audio tracks
// - Maintain all video and subtitle streams
// - Use stream copying to avoid quality loss

const details = () => ({
  id: "Cline_Audio_English_Processor",
  Stage: "Pre-processing",
  Name: "Process Audio Stream Removal",
  Type: "Audio",
  Operation: "Transcode",
  Description: "Processes files to remove duplicate English audio streams using MKVToolsNix or FFmpeg",
  Version: "1.0.0",
  Tags: "pre-processing,audio,english,processing",
  Inputs: []
});

const plugin = (file, librarySettings, inputs, otherArguments) => {
  const response = {
    processFile: false,
    preset: "",
    container: "",
    handBrakeMode: false,
    FFmpegMode: false,
    reQueueAfter: false,
    infoLog: ""
  };

  try {
    // Re-analyze audio streams to determine processing needs
    const audioStreams = file.ffProbeData.streams.filter(stream => stream.codec_type === 'audio');
    
    if (audioStreams.length === 0) {
      response.infoLog += "❓ No audio streams found - skipping\n";
      return response;
    }

    const analysis = {
      englishStreams: [],
      otherLanguageStreams: [],
      undefinedStreams: []
    };

    audioStreams.forEach((stream, index) => {
      const tags = stream.tags || {};
      const language = (tags.language || 'und').toLowerCase();
      
      if (language === 'eng' || language === 'en' || language === 'english') {
        analysis.englishStreams.push({
          index: stream.index,
          streamIndex: index,
          language: language,
          channels: stream.channels || 0,
          codec: stream.codec_name || 'unknown'
        });
      } else if (language === 'und' || language === 'undefined') {
        analysis.undefinedStreams.push({
          index: stream.index,
          streamIndex: index,
          language: language,
          channels: stream.channels || 0,
          codec: stream.codec_name || 'unknown'
        });
      } else {
        analysis.otherLanguageStreams.push({
          index: stream.index,
          streamIndex: index,
          language: language,
          channels: stream.channels || 0,
          codec: stream.codec_name || 'unknown'
        });
      }
    });

    // Skip processing if conditions not met
    if (analysis.undefinedStreams.length > 0 || 
        analysis.englishStreams.length <= 1) {
      response.infoLog += "⚠️ No processing needed - skipping\n";
      return response;
    }

    // Build stream selection for processing
    const streamsToKeep = [];
    streamsToKeep.push(analysis.englishStreams[0]); // Keep first English stream
    streamsToKeep.push(...analysis.otherLanguageStreams); // Keep all other languages

    response.infoLog += `🔄 Processing ${audioStreams.length} audio streams\n`;
    response.infoLog += `✓ Keeping ${streamsToKeep.length} audio streams\n`;
    response.infoLog += `❌ Removing ${analysis.englishStreams.length - 1} duplicate English streams\n`;

    // Determine processing method based on container and preference
    const container = file.container.toLowerCase();
    const isMKV = container === 'mkv' || container === 'matroska';
    const useFFmpeg = !isMKV;

    if (useFFmpeg) {
      // Use FFmpeg for processing
      response.processFile = true;
      response.FFmpegMode = true;
      response.handBrakeMode = false;
      
      // Build FFmpeg stream mapping
      let preset = "-map 0:v"; // Map all video streams
      
      // Map selected audio streams
      streamsToKeep.forEach((stream) => {
        preset += ` -map 0:a:${stream.streamIndex}`;
      });
      
      preset += " -map 0:s?"; // Map subtitle streams if present
      preset += " -c copy"; // Copy streams without re-encoding
      
      response.preset = preset;
      response.container = file.container;
      
    } else {
      // Use MKVToolsNix for MKV files
      response.processFile = true;
      response.FFmpegMode = false;
      response.handBrakeMode = false;
      
      // Build mkvmerge audio track selection
      const audioTracks = streamsToKeep.map(stream => stream.streamIndex).join(',');
      
      response.preset = `-f matroska --audio-tracks ${audioTracks} --video-tracks all --subtitle-tracks all`;
      response.container = "mkv";
    }

    response.reQueueAfter = true;
    return response;

  } catch (error) {
    response.infoLog += `❌ Error processing audio streams: ${error.message}\n`;
    return response;
  }
};

module.exports.details = details;
module.exports.plugin = plugin;
